export const topics = [
  {
    id: "greetings",
    name: "Hallo, Welt!",
    english: "Hello, world!",
    icon: "👋",
    color: "peach",
    goal: "Begrüße jemanden und sag, wie du heißt.",
    words: ["hello", "goodbye", "yes", "no"],
    phrases: ["My name is …", "How are you?"],
    level: "Dein erster Schritt",
  },
  {
    id: "colors",
    name: "Die Welt ist bunt",
    english: "Colors",
    icon: "🎨",
    color: "lavender",
    goal: "Entdecke Farben und benenne sie auf Englisch.",
    words: ["red", "blue", "yellow", "green"],
    phrases: ["It is red.", "What color is it?"],
    level: "Farben entdecken",
  },
  {
    id: "numbers",
    name: "Eins, zwei, three!",
    english: "Numbers",
    icon: "🔢",
    color: "mint",
    goal: "Zähle spielerisch von eins bis fünf.",
    words: ["one", "two", "three", "four", "five"],
    phrases: ["How many?", "I see three."],
    level: "Zählen lernen",
  },
  {
    id: "animals",
    name: "Tierisch gut",
    english: "Animals",
    icon: "🐻",
    color: "sand",
    goal: "Lerne vier Tiere kennen und sag, welches du magst.",
    words: ["cat", "dog", "bird", "bear"],
    phrases: ["It is a cat.", "I like dogs."],
    level: "Tiere kennenlernen",
  },
  {
    id: "family",
    name: "Meine Familie",
    english: "My family",
    icon: "🏡",
    color: "peach",
    goal: "Sprich über Menschen in einer Familie.",
    words: ["mother", "father", "sister", "brother"],
    phrases: ["This is my …"],
    level: "Menschen beschreiben",
  },
  {
    id: "objects",
    name: "Meine kleine Welt",
    english: "Everyday things",
    icon: "🎒",
    color: "mint",
    goal: "Entdecke englische Wörter für Dinge um dich herum.",
    words: ["book", "ball", "pen", "chair"],
    phrases: ["This is a book.", "I have a ball."],
    level: "Dinge entdecken",
  },
  {
    id: "days",
    name: "Eine neue Woche",
    english: "Days of the week",
    icon: "📅",
    color: "lavender",
    goal: "Lerne die Wochentage in kleinen Schritten.",
    words: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    phrases: ["Today is …"],
    level: "Die Woche erkunden",
  },
];
export const topicById = (id) => topics.find((t) => t.id === id);
